name: Bug
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please give your bug report a short and descriptive title.
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: General description of the bug.
      placeholder: Creating a new DAO sets my keyboard on fire!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we replicate the issue?
      placeholder: 1. Navigate to the homepage \n 2. Click Create DAO \n 3. My keyboard bursts into flames
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Video
      description: Any helpful media for investigating the issue.
      placeholder: Not required, but appreciated!
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What server does this bug appear on?
      options:
        - Prod (app.fractalframework.xyz/)
        - Dev (app.dev.fractalframework.xyz/)
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      multiple: true
      description: What browser does this bug appear on?
      options:
        - Chrome (or Chromium based)
        - Firefox
        - Safari
        - All
    validations:
      required: true