sources:
  - name: fractal
    handler:
      graphql: # TODO: Make sure to switch to "production" API url once start hitting limits
        endpoint: https://api.thegraph.com/subgraphs/name/mudrila/fractal

documents:
  - ./src/graphql/DAO.graphql