version: "3"
services:
  blockchain:
    build: docker/blockchain
    ports:
      - "8545:8545"
    env_file:
      - ./docker/.env.tests.local

  webapp:
    build:
      context: ./
      dockerfile: ./docker/webapp/Dockerfile
    ports:
      - "3000:3000"
