blank_issues_enabled: true
contact_links:
  - name: Check out the docs
    url: https://docs.fractalframework.xyz/
    about: Your question might already be answered here!
  - name: Report a Vulnerability
    url: https://github.com/decent-dao/fractal-interface/blob/HEAD/.github/SECURITY.md
    about: Securely report a vulnerability
  - name: Join our Discord
    url: https://chat.fractalframework.xyz/
    about: You can ask product related questions here.