# Development release workflow, generally following the guide posted here
# https://github.com/marketplace/actions/netlify-deploy
name: 'Netlify Development Deploy'
on:
  push: # release on any push to develop
    branches:
      - develop

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # auth token, generated at https://app.netlify.com/user/applications#personal-access-tokens
          NETLIFY_SITE_ID: 'ccad1ffe-d58e-4238-bbca-cc09315855cf' # development site Netlify id (not a private identifier)
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: './.next/'
        env:
          NEXT_PUBLIC_ALCHEMY_TESTING_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_TESTING_API_KEY }}
          NEXT_PUBLIC_INFURA_API_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_API_KEY }}
          NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}