name: NextJS CI/CD

on:
  push:
    branches:
      - develop

jobs:
  deploy-development:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to development environment
        uses: netlify/cli-action@master
        with:
          command: deploy
          args: --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod --json