name: Unit Tests
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  vitest:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up the required Node.js version
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test
